#!/bin/sh
#
# /etc/rc.d/icecast: start/stop icecast daemon
#

case $1 in
start)
	icecast -c /etc/icecast.xml -b
	;;
stop)
	kill -KILL `pidof icecast`
	;;
restart)
	$0 stop
	sleep 2
	$0 start
	;;
*)
	echo "usage: $0 [start|stop|restart]"
	;;
esac

# End of file
